import { describe, it, expect, vi } from 'vitest';
import { generateContractPdf } from '../lib/pdf-generator';
import jsPDF from 'jspdf';

// Mock jsPDF
vi.mock('jspdf', () => {
    const mockJsPDF = {
        setFontSize: vi.fn(),
        setTextColor: vi.fn(),
        text: vi.fn(),
        addImage: vi.fn(),
        save: vi.fn(),
        internal: {
            pageSize: {
                getWidth: () => 210,
            },
        },
    };
    return {
        default: vi.fn(() => mockJsPDF),
    };
});

// Mock jspdf-autotable
vi.mock('jspdf-autotable', () => ({
    default: vi.fn(),
}));

// Mock global Image
global.Image = class {
    src = '';
    onload = () => { };
    onerror = () => { };
    width = 100;
    height = 100;
} as unknown as typeof Image;

// Mock global fetch
global.fetch = vi.fn(() =>
    Promise.resolve({
        blob: () => Promise.resolve(new Blob(['fake-image-data'], { type: 'image/png' })),
    })
) as unknown as typeof fetch;

// Mock FileReader
class MockFileReader {
    result = 'data:image/png;base64,fake-data';
    onloadend = () => { };
    readAsDataURL = () => {
        setTimeout(() => {
            this.onloadend();
        }, 0);
    };
}
global.FileReader = MockFileReader as unknown as typeof FileReader;

// Mock document.createElement for canvas
const mockContext = {
    drawImage: vi.fn(),
};
const mockCanvas = {
    getContext: vi.fn(() => mockContext),
    toDataURL: vi.fn(() => 'data:image/png;base64,resized-fake-data'),
    width: 0,
    height: 0,
};
global.document = {
    createElement: vi.fn((tag) => {
        if (tag === 'canvas') return mockCanvas;
        return {};
    }),
} as unknown as Document;

describe('generateContractPdf', () => {
    const mockTranslations = {
        title: 'Account Balance',
        customerNumber: 'Customer Number',
        date: 'Date',
        depositDate: 'Deposit Date',
        principal: 'Principal',
        timeSinceDeposit: 'Time Since Deposit',
        currentValue: 'Current Value',
        gainSinceDeposit: 'Gain Since Deposit',
        bitcoinAmount: 'Bitcoin Amount',
        bitcoinPrice: 'Bitcoin Price',
        metric: 'Metric',
        value: 'Value',
        generatedBy: 'Generated by',
    };

    it('should generate PDF for ZCHF', async () => {
        const mockData = {
            depositDate: '01.01.2023',
            principal: '1000.00',
            timeSinceDeposit: '1 year',
            currentValue: '1050.00',
            gain: '50.00',
            gainPercentage: '5.00',
        };

        await generateContractPdf('zchf', 'TEST-123', mockData, mockTranslations, 'en');

        // Wait for async operations (fetch, FileReader, Image.onload)
        await new Promise(resolve => setTimeout(resolve, 100));

        expect(jsPDF).toHaveBeenCalled();
    });

    it('should generate PDF for WBTC', async () => {
        const mockData = {
            depositDate: '01.01.2023',
            principal: '50000.00',
            timeSinceDeposit: '1 year',
            currentValue: '60000.00',
            gain: '10000.00',
            gainPercentage: '20.00',
            bitcoinAmount: '1.00000000',
            bitcoinPrice: '60000.00',
        };

        await generateContractPdf('wbtc', 'TEST-456', mockData, mockTranslations, 'en');

        // Wait for async operations
        await new Promise(resolve => setTimeout(resolve, 100));

        expect(jsPDF).toHaveBeenCalled();
    });
});
